### ISSUE TITLE
String format for returned facets appears escaped

### ISSUE THREAD

**Issue by duartegarin** [joaogarin/graphql_search_api#6]
When using facets, the value returned in SolrFacetFilter appears escaped, like "\"institution\"".

**Comment by joaogarin** [comment]
Yeah this is supposed to be addressed in custom code using trim() -> https://www.drupal.org/project/search_api_solr/issues/2886036 its weird. but I will fix it

**Comment by joaogarin** [comment]
fixed in https://github.com/joaogarin/graphql_search_api/commit/5c438e01525560240fda26dad995cf7402c36ee7
